# Bloque HTTP - Redirige todo a HTTPS automáticamente
server {
    listen 80;
    server_name ordpos.duckdns.org;

    location / {
        return 301 https://$host$request_uri;
    }
}

# Bloque HTTPS - Servidor Seguro
server {
    listen 443 ssl;
    server_name ordpos.duckdns.org;

    # Certificados que se inyectarán desde la EC2 mediante el volumen de Docker
    ssl_certificate /etc/letsencrypt/live/ordpos.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ordpos.duckdns.org/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Sirve los archivos estáticos de tu frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Redirige todo lo que empiece con /api/ hacia la IP PRIVADA de tu backend
    location /api/ {
        proxy_pass http://172.31.31.202:3000; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}