server {
    listen 80;
    
    # Sirve los archivos estáticos de tu frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Redirige todo lo que empiece con /api/ hacia la IP PRIVADA de tu backend
    location /api/ {
        # REEMPLAZA ESTA IP por la IP privada real de tu backend y el puerto correcto (3000 u 8080)
        proxy_pass http://172.31.31.202:3000/; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}