name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main # Cambia a master si esa es tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar y Compilar
        run: |
          npm install
          npm run build

      - name: Desplegar Archivos a EC2 (Nginx)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_FRONTEND_HOST }}
          username: ${{ secrets.EC2_FRONTEND_USER }}
          key: ${{ secrets.EC2_FRONTEND_KEY }}
          source: "dist/*"
          target: "/var/www/sistema-frontend"
          strip_components: 1 # Evita que se cree una carpeta llamada 'dist' dentro del EC2