name: Deploy Frontend to S3

on:
  push:
    branches:
      - main # Asegúrate de que sea 'main' o 'master' según tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Corregido también 'node-size' por 'node-version' que es el estándar

      - name: Instalar y Compilar
        run: |
          npm install
          npm run build

      - name: Configurar Credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # 👈 Corregido a punto (.)
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # 👈 Corregido a punto (.)
          aws-region: us-east-1 # Cambia esto si tu bucket está en otra región (ej: sa-east-1)

      - name: Sincronizar con S3
        
        run: |
          aws s3 sync ./dist s3://posbarlacteo-manuel-2026 --delete